### ISSUE TITLE
ExtraOns Will Not Launch On A Server

### ISSUE THREAD

**Issue by MrBreach** [spjoes/Extra-Ons-public#1]
ExtraOns Does Not Work With My 1.12.2 Server, It Crashes On Sartup.
Log:
[crash-2018-02-12_18.38.28-server.txt](https://github.com/spjoes/Extra-Ons-public/files/1721631/crash-2018-02-12_18.38.28-server.txt)

**Comment by D-prog-55** [comment]
This crash is because the server code tries to access client-side only stuff (which isn't present in dedicated servers). Will be fixed in next release.

**Comment by MrBreach** [comment]
Thankyou D-prog-55
